server.port=8080
spring.profiles.include=db-config
########################################################################
#
#     mybatis配置
#
#########################################################################
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mapper/*.xml
########################################################################
#
#     Redis配置
#
#########################################################################
# ===== Redis Cluster =====
spring.redis.timeout=10000

spring.redis.cluster.nodes=192.168.10.85:7001,192.168.10.85:7002,192.168.10.85:7003,192.168.10.85:7004,192.168.10.85:7005,192.168.10.85:7006
spring.redis.cluster.max-redirects=5

# 如果 cluster 设置了密码，打开这个
# spring.redis.password=你的密码

# Jedis 连接池（你现在用的是 jedis）
spring.redis.jedis.pool.max-active=64
spring.redis.jedis.pool.max-idle=16
spring.redis.jedis.pool.min-idle=4
spring.redis.jedis.pool.max-wait=3000




########################################################################
#
#    MQ配置配置
#
#########################################################################
spring.rabbitmq.addresses=192.168.10.85:5671,192.168.10.85:5672,192.168.10.85:5673
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

# 生产上强烈建议开启 confirm + return（保证可靠投递）
spring.rabbitmq.publisher-confirms=true
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

# 消费端手动 ack（更可控）
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=50
spring.rabbitmq.listener.simple.concurrency=2
spring.rabbitmq.listener.simple.max-concurrency=10