###########################################################
#
#                       数据源参数配置-druid
#
###########################################################
initialSize=5
minIdle=5
maxIdle=100
maxActive=20
maxWait=60000
timeBetweenEvictionRunsMillis=60000
minEvictableIdleTimeMillis=300000
###########################################################
#
#                       数据源分片详细配置
#
###########################################################
#打印sql日志
sharding.jdbc.config.sharding.props.sql.show=true
#数据源名称，多数据源以逗号分隔
sharding.jdbc.datasource.names=ds0,ds1,ds2,ds3,ds4,ds5,ds6,ds7,ds8,ds9
###########################################################
#
#                       shardingjdbc--默认分片规则配置--字典表使用
#
###########################################################
#输入加密盐值
jasypt.encryptor.password=salt

###########################################################
#
#                       数据源详细配置
#
###########################################################
#################### 00库配置 ##############################
sharding.jdbc.datasource.ds0.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds0.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds0.url=jdbc:mysql://192.168.10.85:3306/db0?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds0.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds0.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds0.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds0.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds0.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds0.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds0.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds0.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds0.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 01库配置 ##############################
sharding.jdbc.datasource.ds1.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds1.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds1.url=jdbc:mysql://192.168.10.85:3307/db1?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds1.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds1.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds1.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds1.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds1.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds1.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds1.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds1.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds1.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 02库配置 ##############################
sharding.jdbc.datasource.ds2.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds2.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds2.url=jdbc:mysql://192.168.10.85:3308/db2?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds2.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds2.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds2.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds2.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds2.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds2.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds2.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds2.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds2.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 03库配置 ##############################
sharding.jdbc.datasource.ds3.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds3.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds3.url=jdbc:mysql://192.168.10.85:3309/db3?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds3.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds3.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds3.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds3.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds3.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds3.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds3.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds3.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds3.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 02库配置 ##############################
sharding.jdbc.datasource.ds4.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds4.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds4.url=jdbc:mysql://192.168.10.85:3310/db4?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds4.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds4.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds4.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds4.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds4.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds4.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds4.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds4.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds4.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 03库配置 ##############################
sharding.jdbc.datasource.ds5.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds5.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds5.url=jdbc:mysql://192.168.10.85:3311/db5?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds5.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds5.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds5.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds5.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds5.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds5.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds5.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds5.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds5.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 02库配置 ##############################
sharding.jdbc.datasource.ds6.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds6.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds6.url=jdbc:mysql://192.168.10.85:3312/db6?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds6.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds6.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds6.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds6.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds6.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds6.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds6.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds6.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds6.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 03库配置 ##############################
sharding.jdbc.datasource.ds7.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds7.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds7.url=jdbc:mysql://192.168.10.85:3313/db7?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds7.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds7.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds7.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds7.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds7.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds7.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds7.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds7.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds7.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 02库配置 ##############################
sharding.jdbc.datasource.ds8.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds8.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds8.url=jdbc:mysql://192.168.10.85:3314/db8?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds8.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds8.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds8.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds8.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds8.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds8.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds8.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds8.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds8.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}
#################### 03库配置 ##############################
sharding.jdbc.datasource.ds9.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds9.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds9.url=jdbc:mysql://192.168.10.85:3315/db9?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
sharding.jdbc.datasource.ds9.username=root
# 通过ENC(密文)开启密码解密，不使用加密算法时，直接输入原始密码 shardingtest
sharding.jdbc.datasource.ds9.password=root123
# 连接池的配置信息
# 初始化大小，最小，最大
sharding.jdbc.datasource.ds9.initialSize=${initialSize}
# 只需配置minIdle最小连接池数量，maxIdle已经不再使用，配置了也没效果
sharding.jdbc.datasource.ds9.minIdle=${minIdle}
# 最大连接池数量
sharding.jdbc.datasource.ds9.maxActive=${maxActive}
# 配置获取连接等待超时的时间
sharding.jdbc.datasource.ds9.maxWait=${maxWait}
# 用来检测连接是否有效的sql
sharding.jdbc.datasource.ds9.validationQuery=SELECT 1 FROM DUAL
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
sharding.jdbc.datasource.ds9.timeBetweenEvictionRunsMillis=${timeBetweenEvictionRunsMillis}
# 配置一个连接在池中最小生存的时间，单位是毫秒
sharding.jdbc.datasource.ds9.minEvictableIdleTimeMillis=${minEvictableIdleTimeMillis}

###########################################################
#
#                       分库分表配置
#
###########################################################
sharding.jdbc.config.sharding.tables.t_order.actual-data-nodes=ds0.t_order_$->{(0..9).collect{String.format('%02d', it)}},ds1.t_order_$->{(10..19).collect{String.format('%02d', it)}},ds2.t_order_$->{(20..29).collect{String.format('%02d', it)}},ds3.t_order_$->{(30..39).collect{String.format('%02d', it)}},ds4.t_order_$->{(40..49).collect{String.format('%02d', it)}},ds5.t_order_$->{(50..59).collect{String.format('%02d', it)}},ds6.t_order_$->{(60..69).collect{String.format('%02d', it)}},ds7.t_order_$->{(70..79).collect{String.format('%02d', it)}},ds8.t_order_$->{(80..89).collect{String.format('%02d', it)}},ds9.t_order_$->{(90..99).collect{String.format('%02d', it)}}
sharding.jdbc.config.sharding.tables.t_order.database-strategy.standard.sharding-column=order_id
sharding.jdbc.config.sharding.tables.t_order.database-strategy.standard.precise-algorithm-class-name=com.snowalker.shardingjdbc.snowalker.demo.strategy.OrderDbShardingAlgorithm

sharding.jdbc.config.sharding.tables.t_order.table-strategy.standard.sharding-column=order_id
sharding.jdbc.config.sharding.tables.t_order.table-strategy.standard.precise-algorithm-class-name=com.snowalker.shardingjdbc.snowalker.demo.strategy.OrderTableShardingAlgorithm


